# -*-mode:yaml-*-
http-api-listen: 0.0.0.0:8888
http-api-user: root
http-api-pass:
user-agents: # http://www.enterpriseios.com/wiki/UserAgent http://www.useragentstring.com/pages/Mobile%20Browserlist/
  - Mozilla/5.0 (Linux; U; Android 2.3; en-us) AppleWebKit/999+ (KHTML, like Gecko) Safari/999.9
  - Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
  - Mozilla/5.0 (Linux; U; Android 4.0.3; ru-ru; HTC Sensation Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
  - Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3
  - Mozilla/5.0 (iPad; CPU OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3
  - Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3
stubs:
  name: "HLS monitor"
zabbix:
  discovery-path: /var/lib/streamsurfer/discovery.json
  name-template: "{{.Name}}"
  title-template: "{{.Title}}"
unmortal:
  - http://google.com
  - http://ya.ru
db-expired: 24 # hours
defaults:
  probers: 2
  media-probers: 4
  time-between-tasks: 6 # sec
  check-broken-time: 40  # sec
  connect-timeout: 15 # sec
  rw-timeout: 20 # sec
  slow-warning-timeout: 6 # sec
  very-slow-warning-timeout: 12 # sec
  task-ttl: 300 # sec
  error-log: /var/log/streamsurfer/error.log
  http-method: get
  one-segment: true
groups:
  our-new-vod:
    type: hls
    streams:
      - https://x.x.x.x/hls/0f3712c0-b446-11ec-8ef3-3dbeea73260e.m3u8
    probers: 3
    media-probers: 2
    time-between-tasks: 20 # sec
    check-broken-time: 30  # sec
    connect-timeout: 15 # sec
    rw-timeout: 20 # sec
    slow-warning-timeout: 6 # sec
    very-slow-warning-timeout: 12 # sec
    task-ttl: 300 # sec
    error-log: /var/log/streamsurfer/error.log
    http-method: get
    one-segment: true
    parse-method: /[0-9]+/[0-9]+/([-_a-zA-Z0-9.]+)/vod.m3u8
